### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by volkert-fastned** [codacy/helm-ssm#14]
Since a lot of things have been changed in the recently released version 3 of Helm, it seems likely that work will be needed for the SSM plugin to support it. Please add support for Helm 3.

Also, perhaps you can join forces with https://github.com/totango/helm-ssm while you implement an SSM plugin that is compatible Helm 3? After all, both your projects and theirs serve the same purpose.

Thanks for considering. 🙂

**Comment by volkert-fastned** [comment]
See also https://github.com/totango/helm-ssm/issues/6

**Comment by paulopontesm** [comment]
Hello @volkert-fastned 

I just tried this with helm 3 and it worked our of the box.

You just need to make sure you install it with helm 3 because the directory where the plugins are installed is now different. I am using a different binary for helm3 and did it like this:

`helm3 plugin install https://github.com/codacy/helm-ssm/releases/download/latest/helm-ssm-macos.tgz`

**Comment by paulopontesm** [comment]
We found some issues and are working on it on this PR: #28

**Comment by h314to** [comment]
While earlier versions of helm-ssm can still be installed in helm3 as stated above, as of [version 3.0.1](https://github.com/codacy/helm-ssm/releases/tag/3.0.1) we are deprecating helm2 support entirely, and removing dependencies on its APIs.
