### ISSUE TITLE
[CY-2538] prefix from $PREFIX

### ISSUE THREAD

**Issue by alexandr-ushakov-clearscale** [codacy/helm-ssm#21]
how i can add prefix=$PREFIX ???
i want add support env 
something like

helm ssm --env=prod

in amazon ssm i create

/dev/param
/prod/param
/staging/param

how i can do this?...

**Comment by paulopontesm** [comment]
As it is, you probably need to have multiple files for that.

The way we use it, is that we have different AWS accounts for different environments, so we control the using with the AWS_PROFILE environment variable.

Also, since we only want to do overrides, we have a file called `ssm-values.yaml` where we keep only the overrides that come from ssm, these files are usually small. After using the plugin we do:

`$ helm install ... -f ssm-values.yaml`

You can maybe keep `dev-ssm-values.yaml`, `staging-ssm-values.yaml` and `prod-ssm-values.yaml`.

**Comment by alexandr-ushakov-clearscale** [comment]
or use bash script yap?...

Hmm... need add parametr helm ssm --env )

**Comment by paulopontesm** [comment]
But if you want to contribute with some way to adding a "global prefix" or something like that, you are very welcome.
As long as we don't do anything breaking, I think it improves the plugin and I can see how the use case can be useful for more people.

**Comment by paulopontesm** [comment]
Bash scripts are always an option 👍 . Care to share your solution? For future reference

**Comment by machadoit** [comment]
Will be closing this issues as it will be not prioritised for now. Should be re-open if we change priorities or if there is any contribution from the community.
